<?php

namespace BackEndBundle\Repository;

/**
 * PreguntasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntasRepository extends \Doctrine\ORM\EntityRepository
{
}
