<?php

namespace BackEndBundle\Repository;

/**
 * RespuestasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestasRepository extends \Doctrine\ORM\EntityRepository
{
}
