<?php

namespace BackEndBundle\Repository;

/**
 * RespuestasCorrectasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestasCorrectasRepository extends \Doctrine\ORM\EntityRepository
{
}
