back_end:
    resource: "@BackEndBundle/Controller/"
    type:     annotation
    prefix:   /
    
back_end_route:
    resource: "@BackEndBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
